# Generated by Django 6.0.3 on 2026-03-05 14:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('add_date', models.DateField(verbose_name='Дата приема на работу')),
                ('delete_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('dismissed', models.BooleanField(default=False, verbose_name='Уволен')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за сутки')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('tuple', 'Двухместный'), ('triple', 'Трехместный')], max_length=10, verbose_name='Тип номера')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_schedules', to='HotelAPI.employee', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('city_of_origin', models.CharField(max_length=100, verbose_name='Город проживания')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='HotelAPI.room', verbose_name='Номер')),
            ],
            options={
                'unique_together': {('passport_number', 'check_in_date')},
            },
        ),
    ]
