# Generated by Django 6.0.3 on 2026-03-11 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelAPI', '0002_alter_cleaningschedule_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='HotelAPI.room', verbose_name='Номер'),
        ),
    ]
